spring.application.name=demo

# ? DATABASE CONFIG BURADA YOXDUR

server.port=${SERVER_PORT}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
application.jwt.spring.token=${JWT_SECRET}

# MAIL (qal?r)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${APP}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# CloudShell URL-ni bura yaz (sonunda slash olmadan)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true