spring.application.name=demo

# ? DATABASE CONFIG BURADA YOXDUR

server.port=8080

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
application.jwt.spring.token=YjY5Z2I1dzRzNmU4cjN0MXk3dTlvMHA5YThzN2Q2ZjVnNGgzajJrMWwxem94YzR2NmI3bjhtOXEwdzlyOHQ3eTZ1NXY0YzN4MmIxeTltMHE4dzdyNnQ1eTR1M2kybzFwMGE5czhkN2Y2ZzVoNGozajJrMWwxem94YzR2NmI3bjhtOXEwdzlyOHQ3eTZ1NXY0YzN4MmIxeTltMHE4dzdyNnQ1eTR1M2kybzFwMGE5czhkN2Y2ZzVoNGozajJrMWwxem94YzR2NmI3bjhtOXEwdzlyOHQ3eTZ1NXY0YzN4MmIxeTltMHE4dzdyNnQ1eTR1M2kybzFwMGE5czhkN2Y2ZzVoNGozajJrMWwxem94YzR2NmI3bjhtOXEwdzlyOHQ3eTZ1NXY0YzN4MmIxeTltMHE4dzdyNnQ1eTR1M2kybzFwMGE5czhkN2Y2ZzVoNGozajJrMWwxem94YzR2NmI3bjhtOXEwdzlyOHQ3eTZ1NXY0YzN4MmIxeTltMHE4dzdyNnQ1eTR1M2kybzFwMGE5czhkN2Y2ZzVoNGozajJrMWwxem94YY==

# MAIL (qal?r)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sabirmemmedli21152014@gmail.com
spring.mail.password=pxuo xzcp svvw rbqo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# CloudShell URL-ni bura yaz (sonunda slash olmadan)
springdoc.swagger-ui.base-url=https://8080-cs-cd73c805-74e7-4b92-ab0b-47e3eb1b4c29.cs-europe-west4-fycr.cloudshell.dev
server.forward-headers-strategy=framework